        /*********************************************************************************\
        *                                                                                *
        * This file is part of the "Luna-samples" project.                               *
        *                                                                                *
        * The " luna-samples" project is provided under the MIT license (see the         *
        * following Web site for further details: https://mit-license.org/ ).            *
        *                                                                                *
        * Copyright © 2024 Thales Group                                                  *
        *                                                                                *
        **********************************************************************************





        OBJECTIVE : This sample displays the list of all mechanisms enabled/supported by the firmware.
*/





#include <stdio.h>
#include <cryptoki_v2.h>
#include <string.h>
#include <stdlib.h>


// Windows and Linux OS uses different header files for loading libraries.
#ifdef OS_UNIX
        #include <dlfcn.h> // For Unix/Linux OS.
#else
        #include <windows.h> // For Windows OS.
#endif


// Windows uses HINSTANCE for storing library handles.
#ifdef OS_UNIX
        void *libHandle = 0; // Library handle for Unix/Linux
#else
        HINSTANCE libHandle = 0; //Library handle for Windows.
#endif



CK_FUNCTION_LIST *p11Func = NULL;
CK_SLOT_ID slotId = 0; // slot id



// Loads Luna cryptoki library
void loadLunaLibrary()
{
	CK_C_GetFunctionList C_GetFunctionList = NULL;

	char *libPath = getenv("P11_LIB"); // P11_LIB is the complete path of Cryptoki library.
	if(libPath==NULL)
	{
		printf("P11_LIB environment variable not set.\n");
		printf("\n > On Unix/Linux :-\n");
		printf("export P11_LIB=<PATH_TO_CRYPTOKI>");
		printf("\n\n > On Windows :-\n");
		printf("set P11_LIB=<PATH_TO_CRYPTOKI>");
		printf("\n\nExample :-");
		printf("\nexport P11_LIB=/usr/safenet/lunaclient/lib/libCryptoki2_64.so");
		printf("\nset P11_LIB=C:\\Program Files\\SafeNet\\LunaClient\\cryptoki.dll\n\n");
		exit(1);
	}


	#ifdef OS_UNIX
		libHandle = dlopen(libPath, RTLD_NOW); // Loads shared library on Unix/Linux.
	#else
		libHandle = LoadLibrary(libPath); // Loads shared library on Windows.
	#endif
	if(!libHandle)
	{
		printf("Failed to load Luna library from path : %s\n", libPath);
		exit(1);
	}


	#ifdef OS_UNIX
	    C_GetFunctionList = (CK_C_GetFunctionList)dlsym(libHandle, "C_GetFunctionList"); // Loads symbols on Unix/Linux
	#else
		C_GetFunctionList = (CK_C_GetFunctionList)GetProcAddress(libHandle, "C_GetFunctionList"); // Loads symbols on Windows.
	#endif

	C_GetFunctionList(&p11Func); // Gets the list of all Pkcs11 Functions.
	if(p11Func==NULL)
	{
		printf("Failed to load P11 functions.\n");
		exit(1);
	}

	printf ("\n> P11 library loaded.\n");
	printf ("  --> %s\n", libPath);
}



// Always a good idea to free up some memory before exiting.
void freeMem()
{
        #ifdef OS_UNIX
                dlclose(libHandle); // Close library handle on Unix/Linux
        #else
                FreeLibrary(libHandle); // Close library handle on Windows.
        #endif
}



// Checks if a P11 operation was a success or failure
void checkOperation(CK_RV rv, const char *message)
{
	if(rv!=CKR_OK)
	{
		printf("%s failed with Ox%lX\n\n",message,rv);
		p11Func->C_Finalize(NULL_PTR);
		exit(1);
	}
}



// Maps a mechanism code to its CKM_* name.
//
// Every name below is a symbol from the Luna SDK headers rather than a literal,
// so the compiler rejects the table if an SDK upgrade renames or drops one.
// A mechanism the SDK has no name for still prints, as UNKNOWN_MECHANISM
// alongside its raw value.
#define MECH(sym) { (CK_MECHANISM_TYPE)(sym), #sym }

typedef struct
{
	CK_MECHANISM_TYPE code;
	const char *name;
} MechanismName;


static const MechanismName mechanismNames[] =
{
	MECH(CKM_RSA_PKCS_KEY_PAIR_GEN),
	MECH(CKM_RSA_PKCS),
	MECH(CKM_RSA_9796),
	MECH(CKM_RSA_X_509),
	MECH(CKM_MD2_RSA_PKCS),
	MECH(CKM_MD5_RSA_PKCS),
	MECH(CKM_SHA1_RSA_PKCS),
	MECH(CKM_RIPEMD128_RSA_PKCS),
	MECH(CKM_RIPEMD160_RSA_PKCS),
	MECH(CKM_RSA_PKCS_OAEP),
	MECH(CKM_RSA_X9_31_KEY_PAIR_GEN),
	MECH(CKM_RSA_X9_31),
	MECH(CKM_SHA1_RSA_X9_31),
	MECH(CKM_RSA_PKCS_PSS),
	MECH(CKM_SHA1_RSA_PKCS_PSS),
	MECH(CKM_ML_KEM_KEY_PAIR_GEN),
	MECH(CKM_DSA_KEY_PAIR_GEN),
	MECH(CKM_DSA),
	MECH(CKM_DSA_SHA1),
	MECH(CKM_DSA_SHA224),
	MECH(CKM_DSA_SHA256),
	MECH(CKM_ML_KEM),
	MECH(CKM_DSA_SHA3_224),
	MECH(CKM_DSA_SHA3_256),
	MECH(CKM_DSA_SHA3_384),
	MECH(CKM_DSA_SHA3_512),
	MECH(CKM_ML_DSA_KEY_PAIR_GEN),
	MECH(CKM_ML_DSA),
	MECH(CKM_HASH_ML_DSA),
	MECH(CKM_DH_PKCS_KEY_PAIR_GEN),
	MECH(CKM_DH_PKCS_DERIVE),
	MECH(CKM_HASH_ML_DSA_SHA224),
	MECH(CKM_HASH_ML_DSA_SHA256),
	MECH(CKM_HASH_ML_DSA_SHA384),
	MECH(CKM_HASH_ML_DSA_SHA512),
	MECH(CKM_HASH_ML_DSA_SHA3_224),
	MECH(CKM_HASH_ML_DSA_SHA3_256),
	MECH(CKM_HASH_ML_DSA_SHA3_384),
	MECH(CKM_HASH_ML_DSA_SHA3_512),
	MECH(CKM_HASH_ML_DSA_SHAKE128),
	MECH(CKM_HASH_ML_DSA_SHAKE256),
	MECH(CKM_X9_42_DH_KEY_PAIR_GEN),
	MECH(CKM_X9_42_DH_DERIVE),
	MECH(CKM_X9_42_DH_HYBRID_DERIVE),
	MECH(CKM_X9_42_MQV_DERIVE),
	MECH(CKM_SHA256_RSA_PKCS),
	MECH(CKM_SHA384_RSA_PKCS),
	MECH(CKM_SHA512_RSA_PKCS),
	MECH(CKM_SHA256_RSA_PKCS_PSS),
	MECH(CKM_SHA384_RSA_PKCS_PSS),
	MECH(CKM_SHA512_RSA_PKCS_PSS),
	MECH(CKM_SHA224_RSA_PKCS),
	MECH(CKM_SHA224_RSA_PKCS_PSS),
	MECH(CKM_SHA3_256_RSA_PKCS),
	MECH(CKM_SHA3_384_RSA_PKCS),
	MECH(CKM_SHA3_512_RSA_PKCS),
	MECH(CKM_SHA3_256_RSA_PKCS_PSS),
	MECH(CKM_SHA3_384_RSA_PKCS_PSS),
	MECH(CKM_SHA3_512_RSA_PKCS_PSS),
	MECH(CKM_SHA3_224_RSA_PKCS),
	MECH(CKM_SHA3_224_RSA_PKCS_PSS),
	MECH(CKM_RC2_KEY_GEN),
	MECH(CKM_RC2_ECB),
	MECH(CKM_RC2_CBC),
	MECH(CKM_RC2_MAC),
	MECH(CKM_RC2_MAC_GENERAL),
	MECH(CKM_RC2_CBC_PAD),
	MECH(CKM_RC4_KEY_GEN),
	MECH(CKM_RC4),
	MECH(CKM_DES_KEY_GEN),
	MECH(CKM_DES_ECB),
	MECH(CKM_DES_CBC),
	MECH(CKM_DES_MAC),
	MECH(CKM_DES_MAC_GENERAL),
	MECH(CKM_DES_CBC_PAD),
	MECH(CKM_DES2_KEY_GEN),
	MECH(CKM_DES3_KEY_GEN),
	MECH(CKM_DES3_ECB),
	MECH(CKM_DES3_CBC),
	MECH(CKM_DES3_MAC),
	MECH(CKM_DES3_MAC_GENERAL),
	MECH(CKM_DES3_CBC_PAD),
	MECH(CKM_DES3_CBC_PAD_IPSEC_OLD),
	MECH(CKM_DES3_CMAC),
	MECH(CKM_CDMF_KEY_GEN),
	MECH(CKM_CDMF_ECB),
	MECH(CKM_CDMF_CBC),
	MECH(CKM_CDMF_MAC),
	MECH(CKM_CDMF_MAC_GENERAL),
	MECH(CKM_CDMF_CBC_PAD),
	MECH(CKM_DES_OFB64),
	MECH(CKM_DES_OFB8),
	MECH(CKM_DES_CFB64),
	MECH(CKM_DES_CFB8),
	MECH(CKM_MD2),
	MECH(CKM_MD2_HMAC),
	MECH(CKM_MD2_HMAC_GENERAL),
	MECH(CKM_MD5),
	MECH(CKM_MD5_HMAC),
	MECH(CKM_MD5_HMAC_GENERAL),
	MECH(CKM_SHA_1),
	MECH(CKM_SHA_1_HMAC),
	MECH(CKM_SHA_1_HMAC_GENERAL),
	MECH(CKM_RIPEMD128),
	MECH(CKM_RIPEMD128_HMAC),
	MECH(CKM_RIPEMD128_HMAC_GENERAL),
	MECH(CKM_RIPEMD160),
	MECH(CKM_RIPEMD160_HMAC),
	MECH(CKM_RIPEMD160_HMAC_GENERAL),
	MECH(CKM_SHA256),
	MECH(CKM_SHA256_HMAC),
	MECH(CKM_SHA256_HMAC_GENERAL),
	MECH(CKM_SHA224),
	MECH(CKM_SHA224_HMAC),
	MECH(CKM_SHA224_HMAC_GENERAL),
	MECH(CKM_SHA384),
	MECH(CKM_SHA384_HMAC),
	MECH(CKM_SHA384_HMAC_GENERAL),
	MECH(CKM_SHA512),
	MECH(CKM_SHA512_HMAC),
	MECH(CKM_SHA512_HMAC_GENERAL),
	MECH(CKM_SHA3_256),
	MECH(CKM_SHA3_256_HMAC),
	MECH(CKM_SHA3_256_HMAC_GENERAL),
	MECH(CKM_SHA3_224),
	MECH(CKM_SHA3_224_HMAC),
	MECH(CKM_SHA3_224_HMAC_GENERAL),
	MECH(CKM_SHA3_384),
	MECH(CKM_SHA3_384_HMAC),
	MECH(CKM_SHA3_384_HMAC_GENERAL),
	MECH(CKM_SHA3_512),
	MECH(CKM_SHA3_512_HMAC),
	MECH(CKM_SHA3_512_HMAC_GENERAL),
	MECH(CKM_CAST_KEY_GEN),
	MECH(CKM_CAST_ECB),
	MECH(CKM_CAST_CBC),
	MECH(CKM_CAST_MAC),
	MECH(CKM_CAST_MAC_GENERAL),
	MECH(CKM_CAST_CBC_PAD),
	MECH(CKM_CAST3_KEY_GEN),
	MECH(CKM_CAST3_ECB),
	MECH(CKM_CAST3_CBC),
	MECH(CKM_CAST3_MAC),
	MECH(CKM_CAST3_MAC_GENERAL),
	MECH(CKM_CAST3_CBC_PAD),
	MECH(CKM_CAST5_KEY_GEN),
	MECH(CKM_CAST5_ECB),
	MECH(CKM_CAST5_CBC),
	MECH(CKM_CAST5_MAC),
	MECH(CKM_CAST5_MAC_GENERAL),
	MECH(CKM_CAST5_CBC_PAD),
	MECH(CKM_RC5_KEY_GEN),
	MECH(CKM_RC5_ECB),
	MECH(CKM_RC5_CBC),
	MECH(CKM_RC5_MAC),
	MECH(CKM_RC5_MAC_GENERAL),
	MECH(CKM_RC5_CBC_PAD),
	MECH(CKM_IDEA_KEY_GEN),
	MECH(CKM_IDEA_ECB),
	MECH(CKM_IDEA_CBC),
	MECH(CKM_IDEA_MAC),
	MECH(CKM_IDEA_MAC_GENERAL),
	MECH(CKM_IDEA_CBC_PAD),
	MECH(CKM_GENERIC_SECRET_KEY_GEN),
	MECH(CKM_CONCATENATE_BASE_AND_KEY),
	MECH(CKM_CONCATENATE_BASE_AND_DATA),
	MECH(CKM_CONCATENATE_DATA_AND_BASE),
	MECH(CKM_XOR_BASE_AND_DATA),
	MECH(CKM_EXTRACT_KEY_FROM_KEY),
	MECH(CKM_SSL3_PRE_MASTER_KEY_GEN),
	MECH(CKM_SSL3_MASTER_KEY_DERIVE),
	MECH(CKM_SSL3_KEY_AND_MAC_DERIVE),
	MECH(CKM_SSL3_MASTER_KEY_DERIVE_DH),
	MECH(CKM_TLS_PRE_MASTER_KEY_GEN),
	MECH(CKM_TLS_MASTER_KEY_DERIVE),
	MECH(CKM_TLS_KEY_AND_MAC_DERIVE),
	MECH(CKM_TLS_MASTER_KEY_DERIVE_DH),
	MECH(CKM_TLS_PRF),
	MECH(CKM_SSL3_MD5_MAC),
	MECH(CKM_SSL3_SHA1_MAC),
	MECH(CKM_MD5_KEY_DERIVATION),
	MECH(CKM_MD2_KEY_DERIVATION),
	MECH(CKM_SHA1_KEY_DERIVATION),
	MECH(CKM_SHA256_KEY_DERIVATION),
	MECH(CKM_SHA384_KEY_DERIVATION),
	MECH(CKM_SHA512_KEY_DERIVATION),
	MECH(CKM_SHA224_KEY_DERIVATION),
	MECH(CKM_SHA3_256_KEY_DERIVE),
	MECH(CKM_SHA3_224_KEY_DERIVE),
	MECH(CKM_SHA3_384_KEY_DERIVE),
	MECH(CKM_SHA3_512_KEY_DERIVE),
	MECH(CKM_SHAKE_128_KEY_DERIVE),
	MECH(CKM_SHAKE_256_KEY_DERIVE),
	MECH(CKM_PBE_MD2_DES_CBC),
	MECH(CKM_PBE_MD5_DES_CBC),
	MECH(CKM_PBE_MD5_CAST_CBC),
	MECH(CKM_PBE_MD5_CAST3_CBC),
	MECH(CKM_PBE_MD5_CAST5_CBC),
	MECH(CKM_PBE_SHA1_CAST5_CBC),
	MECH(CKM_PBE_SHA1_RC4_128),
	MECH(CKM_PBE_SHA1_RC4_40),
	MECH(CKM_PBE_SHA1_DES3_EDE_CBC),
	MECH(CKM_PBE_SHA1_DES2_EDE_CBC),
	MECH(CKM_PBE_SHA1_RC2_128_CBC),
	MECH(CKM_PBE_SHA1_RC2_40_CBC),
	MECH(CKM_PKCS5_PBKD2),
	MECH(CKM_PBA_SHA1_WITH_SHA1_HMAC),
	MECH(CKM_WTLS_PRE_MASTER_KEY_GEN),
	MECH(CKM_WTLS_MASTER_KEY_DERIVE),
	MECH(CKM_WTLS_PRF),
	MECH(CKM_WTLS_SERVER_KEY_AND_MAC_DERIVE),
	MECH(CKM_WTLS_CLIENT_KEY_AND_MAC_DERIVE),
	MECH(CKM_KEY_WRAP_LYNKS),
	MECH(CKM_KEY_WRAP_SET_OAEP),
	MECH(CKM_CMS_SIG),
	MECH(CKM_ARIA_KEY_GEN),
	MECH(CKM_ARIA_ECB),
	MECH(CKM_ARIA_CBC),
	MECH(CKM_ARIA_MAC),
	MECH(CKM_ARIA_MAC_GENERAL),
	MECH(CKM_ARIA_CBC_PAD),
	MECH(CKM_ARIA_ECB_ENCRYPT_DATA),
	MECH(CKM_ARIA_CBC_ENCRYPT_DATA),
	MECH(CKM_SEED_KEY_GEN),
	MECH(CKM_SEED_ECB),
	MECH(CKM_SEED_CBC),
	MECH(CKM_SEED_MAC),
	MECH(CKM_SEED_MAC_GENERAL),
	MECH(CKM_SEED_CBC_PAD),
	MECH(CKM_SKIPJACK_KEY_GEN),
	MECH(CKM_SKIPJACK_ECB64),
	MECH(CKM_SKIPJACK_CBC64),
	MECH(CKM_SKIPJACK_OFB64),
	MECH(CKM_SKIPJACK_CFB64),
	MECH(CKM_SKIPJACK_CFB32),
	MECH(CKM_SKIPJACK_CFB16),
	MECH(CKM_SKIPJACK_CFB8),
	MECH(CKM_SKIPJACK_WRAP),
	MECH(CKM_SKIPJACK_PRIVATE_WRAP),
	MECH(CKM_SKIPJACK_RELAYX),
	MECH(CKM_KEA_KEY_PAIR_GEN),
	MECH(CKM_KEA_KEY_DERIVE),
	MECH(CKM_FORTEZZA_TIMESTAMP),
	MECH(CKM_BATON_KEY_GEN),
	MECH(CKM_BATON_ECB128),
	MECH(CKM_BATON_ECB96),
	MECH(CKM_BATON_CBC128),
	MECH(CKM_BATON_COUNTER),
	MECH(CKM_BATON_SHUFFLE),
	MECH(CKM_BATON_WRAP),
	MECH(CKM_ECDSA_KEY_PAIR_GEN),
	MECH(CKM_ECDSA),
	MECH(CKM_ECDSA_SHA1),
	MECH(CKM_ECDSA_SHA224),
	MECH(CKM_ECDSA_SHA256),
	MECH(CKM_ECDSA_SHA384),
	MECH(CKM_ECDSA_SHA512),
	MECH(CKM_ECDSA_SHA3_224),
	MECH(CKM_ECDSA_SHA3_256),
	MECH(CKM_ECDSA_SHA3_384),
	MECH(CKM_ECDSA_SHA3_512),
	MECH(CKM_ECDH1_DERIVE),
	MECH(CKM_ECDH1_COFACTOR_DERIVE),
	MECH(CKM_ECMQV_DERIVE),
	MECH(CKM_EC_EDWARDS_KEY_PAIR_GEN),
	MECH(CKM_EC_MONTGOMERY_KEY_PAIR_GEN),
	MECH(CKM_EDDSA),
	MECH(CKM_JUNIPER_KEY_GEN),
	MECH(CKM_JUNIPER_ECB128),
	MECH(CKM_JUNIPER_CBC128),
	MECH(CKM_JUNIPER_COUNTER),
	MECH(CKM_JUNIPER_SHUFFLE),
	MECH(CKM_JUNIPER_WRAP),
	MECH(CKM_FASTHASH),
	MECH(CKM_AES_XTS),
	MECH(CKM_AES_KEY_GEN),
	MECH(CKM_AES_ECB),
	MECH(CKM_AES_CBC),
	MECH(CKM_AES_MAC),
	MECH(CKM_AES_MAC_GENERAL),
	MECH(CKM_AES_CBC_PAD),
	MECH(CKM_AES_CTR),
	MECH(CKM_AES_GCM),
	MECH(CKM_AES_CMAC),
	MECH(CKM_AES_CMAC_GENERAL),
	MECH(CKM_AES_GMAC),
	MECH(CKM_BLOWFISH_KEY_GEN),
	MECH(CKM_BLOWFISH_CBC),
	MECH(CKM_TWOFISH_KEY_GEN),
	MECH(CKM_TWOFISH_CBC),
	MECH(CKM_DES_ECB_ENCRYPT_DATA),
	MECH(CKM_DES_CBC_ENCRYPT_DATA),
	MECH(CKM_DES3_ECB_ENCRYPT_DATA),
	MECH(CKM_DES3_CBC_ENCRYPT_DATA),
	MECH(CKM_AES_ECB_ENCRYPT_DATA),
	MECH(CKM_AES_CBC_ENCRYPT_DATA),
	MECH(CKM_DSA_PARAMETER_GEN),
	MECH(CKM_DH_PKCS_PARAMETER_GEN),
	MECH(CKM_X9_42_DH_PARAMETER_GEN),
	MECH(CKM_AES_OFB),
	MECH(CKM_AES_CFB8),
	MECH(CKM_AES_CFB128),
	MECH(CKM_HSS_KEY_PAIR_GEN),
	MECH(CKM_HSS),
	MECH(CKM_CAST_KEY_GEN_OLD_XXX),
	MECH(CKM_CAST_ECB_OLD_XXX),
	MECH(CKM_CAST_CBC_OLD_XXX),
	MECH(CKM_CAST_MAC_OLD_XXX),
	MECH(CKM_CAST3_KEY_GEN_OLD_XXX),
	MECH(CKM_CAST3_ECB_OLD_XXX),
	MECH(CKM_CAST3_CBC_OLD_XXX),
	MECH(CKM_CAST3_MAC_OLD_XXX),
	MECH(CKM_PBE_MD2_DES_CBC_OLD_XXX),
	MECH(CKM_PBE_MD5_DES_CBC_OLD_XXX),
	MECH(CKM_PBE_MD5_CAST_CBC_OLD_XXX),
	MECH(CKM_PBE_MD5_CAST3_CBC_OLD_XXX),
	MECH(CKM_CONCATENATE_BASE_AND_KEY_OLD_XXX),
	MECH(CKM_CONCATENATE_KEY_AND_BASE_OLD_XXX),
	MECH(CKM_CONCATENATE_BASE_AND_DATA_OLD_XXX),
	MECH(CKM_CONCATENATE_DATA_AND_BASE_OLD_XXX),
	MECH(CKM_XOR_BASE_AND_DATA_OLD_XXX),
	MECH(CKM_EXTRACT_KEY_FROM_KEY_OLD_XXX),
	MECH(CKM_MD5_KEY_DERIVATION_OLD_XXX),
	MECH(CKM_MD2_KEY_DERIVATION_OLD_XXX),
	MECH(CKM_SHA1_KEY_DERIVATION_OLD_XXX),
	MECH(CKM_GENERIC_SECRET_KEY_GEN_OLD_XXX),
	MECH(CKM_CAST5_KEY_GEN_OLD_XXX),
	MECH(CKM_CAST5_ECB_OLD_XXX),
	MECH(CKM_CAST5_CBC_OLD_XXX),
	MECH(CKM_CAST5_MAC_OLD_XXX),
	MECH(CKM_PBE_SHA1_CAST5_CBC_OLD_XXX),
	MECH(CKM_KEY_TRANSLATION),
	MECH(CKM_2DES_KEY_DERIVATION),
	MECH(CKM_INDIRECT_LOGIN_REENCRYPT),
	MECH(CKM_PBE_SHA1_DES3_EDE_CBC_OLD),
	MECH(CKM_PBE_SHA1_DES2_EDE_CBC_OLD),
	MECH(CKM_XOR_BASE_AND_KEY),
	MECH(CKM_HAS160),
	MECH(CKM_KCDSA_KEY_PAIR_GEN),
	MECH(CKM_KCDSA_HAS160),
	MECH(CKM_KCDSA_SHA1),
	MECH(CKM_KCDSA_SHA224),
	MECH(CKM_KCDSA_SHA256),
	MECH(CKM_KCDSA_SHA384),
	MECH(CKM_KCDSA_SHA512),
	MECH(CKM_KCDSA_PARAMETER_GEN),
	MECH(CKM_SHA224_RSA_PKCS_OLD),
	MECH(CKM_SHA224_RSA_PKCS_PSS_OLD),
	MECH(CKM_SHA224_OLD),
	MECH(CKM_SHA224_HMAC_OLD),
	MECH(CKM_SHA224_HMAC_GENERAL_OLD),
	MECH(CKM_SHA224_KEY_DERIVATION_OLD),
	MECH(CKM_DES3_CTR),
	MECH(CKM_AES_GCM_2_20a5d1),
	MECH(CKM_ARIA_CFB8),
	MECH(CKM_ARIA_CFB128),
	MECH(CKM_ARIA_OFB),
	MECH(CKM_ARIA_CTR),
	MECH(CKM_ARIA_GCM),
	MECH(CKM_ARIA_CMAC),
	MECH(CKM_ARIA_CMAC_GENERAL),
	MECH(CKM_SEED_CMAC),
	MECH(CKM_SEED_CMAC_GENERAL),
	MECH(CKM_DES3_CBC_PAD_IPSEC),
	MECH(CKM_AES_CBC_PAD_IPSEC),
	MECH(CKM_ARIA_L_ECB),
	MECH(CKM_ARIA_L_CBC),
	MECH(CKM_ARIA_L_CBC_PAD),
	MECH(CKM_ARIA_L_MAC),
	MECH(CKM_ARIA_L_MAC_GENERAL),
	MECH(CKM_SHA224_RSA_X9_31),
	MECH(CKM_SHA256_RSA_X9_31),
	MECH(CKM_SHA384_RSA_X9_31),
	MECH(CKM_SHA512_RSA_X9_31),
	MECH(CKM_SHA1_RSA_X9_31_NON_FIPS),
	MECH(CKM_SHA224_RSA_X9_31_NON_FIPS),
	MECH(CKM_SHA256_RSA_X9_31_NON_FIPS),
	MECH(CKM_SHA384_RSA_X9_31_NON_FIPS),
	MECH(CKM_SHA512_RSA_X9_31_NON_FIPS),
	MECH(CKM_RSA_X9_31_NON_FIPS),
	MECH(CKM_RSA_FIPS_186_3_AUX_PRIME_KEY_PAIR_GEN),
	MECH(CKM_RSA_FIPS_186_3_PRIME_KEY_PAIR_GEN),
	MECH(CKM_SEED_CTR),
	MECH(CKM_KCDSA_HAS160_NO_PAD),
	MECH(CKM_KCDSA_SHA1_NO_PAD),
	MECH(CKM_KCDSA_SHA224_NO_PAD),
	MECH(CKM_KCDSA_SHA256_NO_PAD),
	MECH(CKM_KCDSA_SHA384_NO_PAD),
	MECH(CKM_DES3_X919_MAC),
	MECH(CKM_KCDSA_SHA512_NO_PAD),
	MECH(CKM_ECDSA_KEY_PAIR_GEN_W_EXTRA_BITS),
	MECH(CKM_ECDSA_GBCS_SHA256),
	MECH(CKM_AES_KW),
	MECH(CKM_AES_KWP),
	MECH(CKM_TDEA_KW),
	MECH(CKM_TDEA_KWP),
	MECH(CKM_AES_CBC_CMAC_WRAP),
	MECH(CKM_EXTMU_ML_DSA),
	MECH(CKM_AES_CBC_PAD_EXTRACT),
	MECH(CKM_AES_CBC_PAD_INSERT),
	MECH(CKM_AES_CBC_PAD_EXTRACT_FLATTENED),
	MECH(CKM_AES_CBC_PAD_INSERT_FLATTENED),
	MECH(CKM_AES_CBC_PAD_EXTRACT_DOMAIN_CTRL),
	MECH(CKM_AES_CBC_PAD_INSERT_DOMAIN_CTRL),
	MECH(CKM_PLACE_HOLDER_FOR_ERACOME_DEF_IN_SHIM),
	MECH(CKM_DES2_DUKPT_IPEK),
	MECH(CKM_DES2_DUKPT_PIN),
	MECH(CKM_DES2_DUKPT_MAC),
	MECH(CKM_DES2_DUKPT_MAC_RESP),
	MECH(CKM_DES2_DUKPT_DATA),
	MECH(CKM_DES2_DUKPT_DATA_RESP),
	MECH(CKM_ECIES),
	MECH(CKM_XOR_BASE_AND_DATA_W_KDF),
	MECH(CKM_NIST_PRF_KDF),
	MECH(CKM_PRF_KDF),
	MECH(CKM_SM3),
	MECH(CKM_SM3_HMAC),
	MECH(CKM_SM3_HMAC_GENERAL),
	MECH(CKM_SM3_KEY_DERIVATION),
	MECH(CKM_SM4_KEY_GEN),
	MECH(CKM_SM4_ECB),
	MECH(CKM_SM4_CBC),
	MECH(CKM_SM4_CBC_PAD),
	MECH(CKM_SM2_KEY_PAIR_GEN),
	MECH(CKM_SM2DSA),
	MECH(CKM_SM3_SM2DSA),
	MECH(CKM_SHA1_SM2DSA),
	MECH(CKM_SHA224_SM2DSA),
	MECH(CKM_SHA256_SM2DSA),
	MECH(CKM_SHA384_SM2DSA),
	MECH(CKM_SHA512_SM2DSA),
	MECH(CKM_EDDSA_NACL),
	MECH(CKM_SHA1_EDDSA_NACL),
	MECH(CKM_SHA224_EDDSA_NACL),
	MECH(CKM_SHA256_EDDSA_NACL),
	MECH(CKM_SHA384_EDDSA_NACL),
	MECH(CKM_SHA512_EDDSA_NACL),
	MECH(CKM_SHA1_EDDSA),
	MECH(CKM_SHA224_EDDSA),
	MECH(CKM_SHA256_EDDSA),
	MECH(CKM_SHA384_EDDSA),
	MECH(CKM_SHA512_EDDSA),
	MECH(CKM_BIP32_MASTER_DERIVE),
	MECH(CKM_BIP32_CHILD_DERIVE),
	MECH(CKM_KEY_TRANSLATE),
	MECH(CKM_MILENAGE),
	MECH(CKM_MILENAGE_RESYNC),
	MECH(CKM_MILENAGE_AUTS),
	MECH(CKM_TUAK),
	MECH(CKM_TUAK_RESYNC),
	MECH(CKM_TUAK_AUTS),
	MECH(CKM_COMP128),
	MECH(CKM_SHAKE_128),
	MECH(CKM_SHAKE_256),
	MECH(CKM_KECCAK_224),
	MECH(CKM_KECCAK_256),
	MECH(CKM_KECCAK_384),
	MECH(CKM_KECCAK_512),
	MECH(CKM_SHA3_224_EDDSA),
	MECH(CKM_SHA3_256_EDDSA),
	MECH(CKM_SHA3_384_EDDSA),
	MECH(CKM_SHA3_512_EDDSA),
};


static const char *mechanismName(CK_MECHANISM_TYPE mech)
{
	size_t index;
	for(index=0; index<sizeof(mechanismNames)/sizeof(*mechanismNames); index++)
	{
		if(mechanismNames[index].code==mech)
			return mechanismNames[index].name;
	}
	return "UNKNOWN_MECHANISM";
}



// This function displays the list of all mechanisms supported by the firmware.
void getMechanisms()
{
	CK_MECHANISM_TYPE *mechList = NULL;
	CK_ULONG listSize = 0;
	CK_ULONG ctr = 0;

	checkOperation(p11Func->C_GetMechanismList(slotId, NULL_PTR, &listSize), "C_GetMechanismList");
	mechList = (CK_MECHANISM_TYPE_PTR)malloc(listSize * sizeof(CK_MECHANISM_TYPE));
	if(mechList==NULL)
	{
		printf("Failed to allocate memory for the mechanism list.\n");
		p11Func->C_Finalize(NULL_PTR);
		exit(1);
	}
	checkOperation(p11Func->C_GetMechanismList(slotId, mechList, &listSize), "C_GetMechanismList");
	printf("\n> Supported Mechanisms - \n");
	for(ctr=0; ctr<listSize; ctr++)
	{
		printf("%lu. | %s | 0x%08lX\n", (unsigned long)ctr,
			mechanismName(mechList[ctr]), (unsigned long)mechList[ctr]);
	}
	free(mechList);
}



// Prints the syntax for executing this code.
void usage(const char exeName[30])
{
	printf("\nUsage :-\n");
	printf("%s <slot_number>\n\n", exeName);
}



int main(int argc, char **argv[])
{
	printf("\n%s\n", (char*)argv[0]);
	if(argc<2) {
		usage((char*)argv[0]);
		exit(1);
	}
	slotId = atoi((const char*)argv[1]);

	loadLunaLibrary();
	checkOperation(p11Func->C_Initialize(NULL_PTR), "C_Initialize"); // Initialize cryptoki.
	getMechanisms();
	checkOperation(p11Func->C_Finalize(NULL_PTR), "C_Finalize"); // finalize cryptoki.
	freeMem();
	return 0;
}
